# Generated by Django 3.2.13 on 2022-07-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zartekapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_created',
        ),
    ]
