# Generated by Django 3.2.13 on 2022-07-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zartekapp', '0003_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images/'),
        ),
    ]
