# Generated by Django 3.2.13 on 2022-07-22 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zartekapp', '0004_task_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_desc',
            new_name='post_desc',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='post_name',
        ),
    ]
